#!/usr/bin/env bash
# Set up a web server with Nginx and listen on port 80.
# Use "Hello World" to create a default index.html file.

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
