#!/usr/bin/env bash
# Set up Nginx to Redirect URLs

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/redirect_me
sudo service nginx restart
