#!/usr/bin/env bash
# Nginx configured with custom 404 page

# Verify that Nginx is installed.
if [ ! -x "$(command -v nginx)" ]; then
    echo "Nginx is not installed. Please run the 1-install_nginx_web_server script first."
    exit 1
fi

# Configuration file for the personalized 404 page.
echo "server {" > /etc/nginx/sites-available/custom_404
echo "    listen 80 default_server;" >> /etc/nginx/sites-available/custom_404
echo "    listen [::]:80 default_server ipv6only=on;" >> /etc/nginx/sites-available/custom_404
echo "    root /usr/share/nginx/html;" >> /etc/nginx/sites-available/custom_404
echo "    error_page 404 /custom_404.html;" >> /etc/nginx/sites-available/custom_404
echo "    location = /custom_404.html {" >> /etc/nginx/sites-available/custom_404
echo "        internal;" >> /etc/nginx/sites-available/custom_404
echo "        echo \"Ceci n'est pas une page\";" >> /etc/nginx/sites-available/custom_404
echo "    }" >> /etc/nginx/sites-available/custom_404
echo "}" >> /etc/nginx/sites-available/custom_404

# Make new configuration available create a symbolic link.
ln -sf /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# To apply changes restart Nginx.
service nginx restart
