#!/usr/bin/env bash
# Config new IP addresses for facebook.com and localhost. 8.8.8.8 and 127.0.0.2
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
