#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed argument `start`:
#     manage_my_process
#     Containings its PID in /var/run/my_process.pid
#     Displays "manage_my_process started"
#   When passed argument `stop`:
#     manage_my_process
#     file /var/run/my_process.pid
#     Displays "manage_my_process stopped"
#   When passed argument `restart`:
#     manage_my_process
#     Deletes the file /var/run/my_process.pid
#     Starts manage_my_process
#     file containing its PID in /var/run/my_process.pid
#     Displays "manage_my_process restarted"
#   no arguments passed "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]
then
	    ./manage_my_process &
	        touch /var/run/my_process.pid
		    echo "$!" > /var/run/my_process.pid
		        echo "manage_my_process started"
		elif [ "${1}" == "stop" ]
		then
			    echo "manage_my_process stopped"
			        kill "$(cat /var/run/my_process.pid)"
				    rm /var/run/my_process.pid
			    elif [ "${1}" == "restart" ]
			    then
				        kill "$(cat /var/run/my_process.pid)"
					    rm /var/run/my_process.pid
					        ./manage_my_process &
						    touch /var/run/my_process.pid
						        echo "$!" > /var/run/my_process.pid
							    echo "manage_my_process restarted"
						    else
							        echo "Usage: manage_my_process {start|stop|restart}"
fi
