#!/usr/bin/env bash
# Config new IP addresses for facebook and localhost.
#   - facebook.com resolves 8.8.8.8
#   - localhost resolves 127.0.0.2
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
